dist: xenial
sudo: required
language: node_js
node_js:
  - "6"
before_install:
  - echo $(which npm)
  - npm i -g npm@5.1.0
  - npm --version
  - echo $(which npm)
  - sudo $(which npm) --version
  - npm install
  - cd server
  - npm --version
  - sudo $(which npm) --version
  - ls
install:
  - cd ../client
  - ls
script:
  - cd ..
  - ls
