dist: xenial
sudo: required
language: node_js
node_js:
  - "6"
before_install:
  - npm install n
  - sudo ./node_modules/.bin/n stable
  - rm -rf ~/.nvm
  - npm --version
  - node --version
  - sudo npm --version
  - npm install
  - cd server
  - npm --version
  - sudo $(which npm) --version
  - ls
install:
  - cd ../client
  - ls
script:
  - cd ..
  - ls
