dist: xenial
sudo: required
language: node_js
node_js:
  - "6"
before_install:
  - echo $(which npm)
  - echo $(which node)
  - echo $(type -P node)
  - echo $(type -P npm)
  - sudo $(type -P npm) install
  - cd server
  - npm --version
  - sudo $(which npm) --version
  - ls
install:
  - cd ../client
  - ls
script:
  - cd ..
  - ls
